### ISSUE TITLE
code-generator is missing from this repo

### ISSUE THREAD

**Issue by kargakis** [kubernetes/sample-controller#6]
1. git cloned this repo
2. changed the types to my own
3. removed all generated files (rm -rf pkg/client pkg/apis/prow/v1/zz_generated.deepcopy.go)
4. ./hack/update-codegen.sh does not work because code-generator is not vendored in this repo
5. pushd vendor/k8s.io
6. git clone https://github.com/kubernetes/code-generator
7. popd; ./hack/update-codegen.sh now works

I didn't expect to do 5-7. I assumed that since this is a standalone repo, code generation should work ootb. Intentional?

@munnerz @sttts

**Comment by sttts** [comment]
> Intentional?

Intentional? no. Known? yes. Godeps does not do it itself and the publisher does not fix it up (but could).

**Comment by munnerz** [comment]
Yep this is a bit of a tricky one right now - does Godeps support explicitly vendoring a package that the project doesn't actually depend upon?

Even if we make the publisher do this, we need to make sure a `godeps save ./...` in future doesn't wipe out the code-generator dependency (thinking about end-users who might copy and paste this repo to start their own)

**Comment by sttts** [comment]
> (thinking about end-users who might copy and paste this repo to start their own)

An hack/update-godeps.sh could help I think. But I wonder whether we really have to protect the users from the vendoring tools so much. The published repo should of course work. But if users copy the code, they have to know their vendoring tool of choice. And yes, these are a pain in Goland.

**Comment by kargakis** [comment]
Another option is to create a dependency link between the generator and the sample repo with an empty import. Could that work?
```go
import _ "k8s.io/code-generator"
```

**Comment by kargakis** [comment]
Or `hack/update-codegen.sh` can ensure the generator is cloned in the directory it expects to find it.

**Comment by sttts** [comment]
> Or hack/update-codegen.sh can ensure the generator is cloned in the directory it expects to find it.

Which means it must be aware of its branch and pick the right version. Don't like that either. We need a sane vendoring tool like dep that can reference extra repos.

**Comment by kargakis** [comment]
> Which means it must be aware of its branch and pick the right version. Don't like that either. We need a sane vendoring tool like dep that can reference extra repos.

@sttts today `code-generator` and `sample-controller` follow the release branches of `kubernetes/kubernetes`. Unless, that is going to change in the future, I think `hack/update-codegen.sh` should try to checkout the same branch in `code-generator`that is already checkout out in `sample-controller` when the script runs. Seems like a viable short-term fix, `dep` is unlike to be used anytime soon.

**Comment by sttts** [comment]
> dep is unlike to be used anytime soon.

You might be surprised soon ;)

**Comment by carolynvs** [comment]
I am using dep to get started on a fork of this repo. Here's my config for vendoring the code generator (relies on dep v0.4.1+):

```toml
required = [
  "k8s.io/code-generator/cmd/client-gen"
]

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.9.2"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false
    go-tests = false

  [[prune.project]]
    name = "k8s.io/gengo"
    unused-packages = false
    non-go = false
    go-tests = false
```

I haven't gotten to the point where everything is working so that may need to change some more. 😀
